### ISSUE TITLE
example not working with assume role session

### ISSUE THREAD

**Issue by carmithersh** [aws-samples/sigv4a-signing-examples#10]
is this code supposed to be working with an assumed role credentials? with assumed role, I also have a session token, which is not part of the examples. 
so, if I do the call exactly as in the example I get:
 <Error>
        <Type>Sender</Type>
        <Code>InvalidClientTokenId</Code>
        <Message>The security token included in the request is invalid.</Message>
    </Error>

but if I add the session token, I get:

<Error>
        <Type>Sender</Type>
        <Code>SignatureDoesNotMatch</Code>
        <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>
    </Error>

can you please add an example of creating the signed authorization with the assumed role session token?

**Comment by pritamrungta** [comment]
Hi @carmithersh 

Did you find any solution for this?

I am getting the following error with assumed role token in credentials:

<img width="1162" alt="image" src="https://github.com/aws-samples/sigv4a-signing-examples/assets/59230352/15f2ae69-768f-4b01-b475-3c604c4f5152">

**Comment by carmithersh** [comment]
eventually ew were able to complete our tasks, but as so much time passed, I am not sure about this specific issue
