### ISSUE TITLE
significant increased response times using sigv4a and nodejs

### ISSUE THREAD

**Issue by jasondrury22** [aws-samples/sigv4a-signing-examples#11]
Has anyone noticed a significant increase in response times using sigv4a and nodejs vs sigv4 ?  It appears to be around 100ms or more.  I also noticed no increase when using a python client and sigv4a.  I have tried fetch and https.request to make the calls.

**Comment by jasondrury22** [comment]
Hi @lovaarte thanks for responding.  Sorry I forgot that I made this comment.  Actually there was no issue with sigv4a at all.  It was how we were implementing something.  From what I remember we were instantiating the AwsCredentialsProvider for every request which became an issue for greater loads.

**Comment by lovaarte** [comment]
I see, yeah that would be a more costly operation. Based on my testing, the signing operation itself, in node, I saw the performance in low single digit, around 2-5ms. End-to-end request would potentially have many dependencies, source/destination locations, network jitter, etc.
