### ISSUE TITLE
How to pass body in request in javascript example

### ISSUE THREAD

**Issue by Leonardo-94** [aws-samples/sigv4a-signing-examples#17]
Hi, I tried all to make javascript (node) example 3 work, passing a simple body, such as 

`{ "data": "hello world" }`

inside 

`new HttpRequest(method, endpoint);`

of sigv4a_sign.js file, but it didn't work, because my server didn't receive any body. Could you please write me an example of how to pass a body that for sure will be signed and passed in an after request.

Thank you in advance

**Comment by lovaarte** [comment]
Hi @Leonardo-94 , are you talking about a POST/PUT request? If so, I can look to add an example, but in meanwhile you can find an example in java and maybe derive it https://github.com/aws-samples/sigv4a-signing-examples/tree/main/java#Example-5. Else please clarify what exactly you're trying to do.

**Comment by Leonardo-94** [comment]
For now I solved it passing the body already hashed inside:

```
const crypto = require('crypto');
...
const config = {
  ...
  signed_body_value: crypto.createHash("sha256").update(JSON.stringify(body)).digest("hex"),
  ...
}
```

in the file sigv4a_sign.js

So it's ok for me now, but i let you decide whether to close the issue or not, cause the initial problem is not exactly solved.

**Comment by lovaarte** [comment]
Thanks for looking into it. Probably worth adding a POST/PUT example. Interestingly, in node it put's the responsibility on the client to hash it.
