### ISSUE TITLE
The nodejs version does not work 

### ISSUE THREAD

**Issue by entest-hai** [aws-samples/sigv4a-signing-examples#7]
Please check the signva_sign.js does not work, it just create an empty header 

```js 
HttpHeaders {}
```

**Comment by lovaarte** [comment]
What is your exact code that doesn't work for you, e.g. produces the result you're describing?

**Comment by crowecawcaw** [comment]
+1 the example code doesn't work as written. Consider running it, fixing any issues, and updating the examples. In example 2, the example imports `sigV4ASignBasic` but uses `sigV4ASign`.

I also was not able to get the example working even after fixing a few things with the `aws-crt` version in the package.json. I updated the version to 1.21 which got it working. Considering updating the package.json to include a version range so it gets future updates, like: `"aws-crt": "^1.21.1"`

**Comment by lovaarte** [comment]
@crowecawcaw thanks, should be fixed now.
